### ISSUE TITLE
OSX: conda-forge libpng is not selected

### ISSUE THREAD

**Issue by kmuehlbauer** [conda-forge/wradlib-feedstock#8]
Having gdal as dependency, the correct libpng from conda-forge channel isn't picked up.

@ocefpaf, @jjhelmus Is this the with the `conda-build 1.20.1` glitch? How do I re-render the feedstock and incorporate those workaround-changes? Didn't do that before.

**Comment by ocefpaf** [comment]
@kmuehlbauer which version of `gdal` is expected here 1 or 2? Can you check if our version is picked by the solver? If so then https://github.com/conda-forge/gdal-feedstock/pull/52 should fix it.

I did all the pinning for `gdal 1.11.4`, but since I never used `gdal 2` I completely forgot to propagate the changes there. Now that `gdal 2` is on master we should fix that. (See https://github.com/conda-forge/gdal-feedstock/issues/51 too.)

**Comment by kmuehlbauer** [comment]
@ocefpaf Yes, using gdal 2.1.0 here (should pickup that anyway). And yes, the gdal2.1.0 is selected by the solver, but libpng 1.6.17 is picked instead of 1.6.21. Thanks for fixing in gdal-feedstock.

**Comment by kmuehlbauer** [comment]
@ocefpaf, doesn't solve the issue, seems I have to import the latest smithy changes (conda build 1.20.1 problem)

**Comment by ocefpaf** [comment]
@kmuehlbauer how did you test https://github.com/conda-forge/gdal-feedstock/pull/52? I just merged it and the binaries should be up in a while.

**Comment by kmuehlbauer** [comment]
@ocefpaf, :laughing: Just looked at the green lights and didn't think about the merge.  Will try later, thanks!

**Comment by ocefpaf** [comment]
> @ocefpaf, :laughing: Just looked at the green lights and didn't think about the merge.  Will try later, thanks!

Been there, done that. (More times than I care to admit :stuck_out_tongue_winking_eye:)

**Comment by kmuehlbauer** [comment]
@ocefpaf restarted Travis, picked up correct gdal but default channel libpng. I'll not be active for some days, so this is not this urgent.

**Comment by ocefpaf** [comment]
> @ocefpaf restarted Travis, picked up correct gdal but default channel libpng. I'll not be active for some days, so this is not this urgent.

Can you point me to the logs?  `libpng` is properly pinned in the build `1`, maybe your setup is still installing build `0` for some reason.

**Comment by kmuehlbauer** [comment]
This is the first of three builds:
https://travis-ci.org/conda-forge/wradlib-feedstock/jobs/127740753

It picked up `gdal 2.1.0-np111py27_1` which should be correct, but `libpng 1.6.17-0` is selected.

**Comment by ocefpaf** [comment]
Got it. Sadly that is fair game as we are pinning `gdal` to `libpng 1.6*` and not `libpng 1.6.21` :unamused: 

@pelson do you think it is OK to change our `libpng` pinning rules to `1.6.21` exactly (or `>1.6.17`)?

**Comment by kmuehlbauer** [comment]
@ocefpaf, I thought, that packages in conda-forge override default-channel. Did I got that wrong?

**Comment by ocefpaf** [comment]
> @ocefpaf, I thought, that packages in conda-forge override default-channel. Did I got that wrong?

Override? No. The higher version should be chosen? Yes. However, the details on how the solver chooses the overall versions are not that simple. Sometime there are decisions to downgrade certain packages to promote a general upgrade. So we need to protect our stack by pinning to be bone :unamused:

**Comment by kmuehlbauer** [comment]
> Override? No. The higher version should be chosen? Yes.

That was what I wanted to say ...

I wonder why this worked on linux and windows.

**Comment by ocefpaf** [comment]
> I wonder why this worked on linux and windows.

Me too. I only experience this behavior on OS X and in many different situations.

**Comment by pelson** [comment]
> @pelson do you think it is OK to change our libpng pinning rules to 1.6.21 exactly (or >1.6.17)?

Not ideally. We should investigate _why_ conda is doing it. I suspect there is a package somewhere which is pinning something too stringently impacting the solver's decision.

_Update_: Looks like a lot of `defaults` is pinning right down to the minor version of libpng. @msarahan, do you know if there is a good reason for this? Do you happen to know if libpng break ABI compatibility between patch versions?

**Comment by kmuehlbauer** [comment]
OK, I thought a bit about `build-` and `run-dependencies`. Came to the conclusion that we only need `numpy` as build dependency. I quickly checked this locally, it works actually. @ocefpaf, @pelson, nevertheless, is there some more in-depth docs about build and run dependencies (and difference)? Just before I fix this...

**Comment by ocefpaf** [comment]
> I quickly checked this locally, it works actually. @ocefpaf, @pelson, nevertheless, is there some more in-depth docs about build and run dependencies (and difference)? Just before I fix this...

Not really as that has more to do with each package than conda/conda-forge. I don't known anything about `wradlib`. With that said, if `numpy` is a required `build` dependency there is a change we should be using `numpy x.x` instead of just numpy. Can you check if there are compiled extensions that depends  on numpy ABI?

**Comment by kmuehlbauer** [comment]
wradlib setup.py uses numpy.distutils.misc_util for configuration. This is afaics the only build-dependency of wradlib. wradlib is pure python, but uses numpy, scipy, matplotlib, gdal, etc. etc. to run.

It's not really clear to me, what is a build dependency and what is a run-dependency.

**Comment by ocefpaf** [comment]
@kmuehlbauer that is complicated as it depends on the language at hand and how the software is prepared to be packaged. Python sometime require a lot of dependencies to be available at build time even though they are not really needed just b/c people imports the package to get the version in the `setup.py`.

**Comment by msarahan** [comment]
> Update: Looks like a lot of defaults is pinning right down to the minor version of libpng. @msarahan, do you know if there is a good reason for this? Do you happen to know if libpng break ABI compatibility between patch versions?

@pelson I have seen several instances of pinning libpng to 1.2.\* - is that what you mean?  Are there more specific pins than that?  If so, that might be something that needs fixing.  I don't recall why this is/was necessary.  I want to say it has been this way since I got here.

**Comment by ocefpaf** [comment]
@msarahan the issue is that files lile http://anaconda.org/anaconda/freetype/2.5.2/download/osx-64/freetype-2.5.2-1.tar.bz2 have a require metadata that specifies versions like this:

``` yaml
libpng-1.5.13-1
zlib-1.2.8-0
```

Not only minor version, but also the build number is pinned.
